### ISSUE TITLE
Using RJ45 instead of Wifi

### ISSUE THREAD

**Issue by afrocubanito** [digitalbird01/DigitalBird-Camera-Slider#2]
First thank you for your awesome project. 
Do you think it’s possible to modify the pan/tilt head and ptzplus to work with rj45, for better latency and longest distance? I could use a network router, to connect, pan/tilt, camera settings, and camera videos feeds . My cameras can work inside a Lan and can send rtsp for monitoring video and receive http request, for, iso,shutter,etc.  Best regards Cordaliss

**Comment by digitalbird01** [comment]
Thanks for the interest
There is a new PTZ head coming very soon with VISCA IP and POE power which supports OBS and vMix. Subscribe to the YouTube channel to be kept up to date with this.

**Comment by afrocubanito** [comment]
Hello and thank you for your answer,

This is a good news. I presume you will build a new remote controller to work with it ?

Thank you to make Multicam Production Possible for solo entrepreneur, like me.

Best regards
Cordaliss

**Comment by digitalbird01** [comment]
Hi
To begin with the Digital Bird PTZ controller will  only be for WIFI
control however this may well change in the future. The new head has been
tested with OBS and vMix which both offer control on screen or using a
games controller. The new head may also be controlled using other console
PTZ controllers which support VISCA over IP using UDP however this has not
been tested since I do not own any of those devices to test with.
You will still need the WIFI controller in order to set the device's IP
address and use all the heads WIFI functionality. In future the WIFI
controller will also be required to set up some other advanced PTZ
features for which there is no VISCA command set.
